baseURL = "https://tuosito.github.io/"  # Cambia questo con l'URL del tuo sito se usi GitHub Pages
languageCode = "it"
title = "Il Punto Digitale"
theme = "PaperMod"
[pagination]
pagerSize = 10

[params]
  author = "Redazione AI"
  description = "Un giornale italiano generato con intelligenza artificiale"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  hideFooter = false
  defaultTheme = "auto" # dark, light, auto

[params.homeInfoParams]
  Title = "Benvenuto su Giornale Politico AI"
  Content = "Notizie generate con intelligenza artificiale, aggiornate quotidianamente. Leggi, condividi e rimani informato."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "politica"
    name = "Politica"
    url = "/categories/politica/"
    weight = 2

  [[menu.main]]
    identifier = "chi-siamo"
    name = "Chi siamo"
    url = "/chi-siamo/"
    weight = 3

  [[menu.main]]
    identifier = "contatti"
    name = "Contatti"
    url = "/contatti/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
